### ISSUE TITLE
에러처리

### ISSUE THREAD

**Issue by kwangddang** [woowa-techcamp-2022/android-banchan-09#105]
### Overview

- [x] 이슈 1
- [x] 이슈 2

**Comment by Zzu-h** [comment]
에러처리를 어떻게 할지 논의가 필요할 듯합니다!
비어있는 content를 보여주며 로딩화면을 닫는 로직과 toast를 보여주는 것까지는 되어있으나 구체적인 에러 로직을 정하지 않아서 두겠습니다..!!
