### ISSUE TITLE
Data 반환 형 수정

### ISSUE THREAD

**Issue by kwangddang** [woowa-techcamp-2022/android-banchan-09#85]
### Overview

- [ ] Domain에서 반환할 때 DataResponse라는 클래스로 반환
- [ ] ViewModel에서 DataResponse를 UiState로 변환

**Comment by Zzu-h** [comment]
현재 이 이슈는 다른 pr들을 머지한 후에 작업이 가능할 것 같아서
오늘 작업류에서 제외하도록 하겠습니다

ps. 작업하다가 생각보다 viewmodel들을 많이 건들이게 돼서.. 다시 돌리고 여러 충돌들을 방지하고자 두게되었어요 ㅎ..

**Comment by kwangddang** [comment]
#83  이 이슈도 같은 이유로 일단 미뤄두어야 할 거 같습니다!

**Comment by Zzu-h** [comment]
이 이슈는 Result로 통합하고, viewmodel에서 onSuccess와 onFaliure로 관리하기로 했기에 이슈를 닫습니다
